" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)


"语法高亮度显示
  syntax on
"去掉有关vi一致性模式，避免以前版本的一些bug和局限
  set nocompatible
"显示行号
  set number
"检测文件的类型
  filetype on
"记录历史的行数
  set history=1000
"背景使用黑色
  set background=dark
"vim使用自动对起，也就是把当前行的对起格式应用到下一行
  set autoindent
"依据上面的对起格式，智能的选择对起方式，对于类似C语言编
  set smartindent
"设置Windows风格的C/C++自动缩进,第一行设置tab键为4个空格，第二行设置当行之间交错时使用4个空格
  set tabstop=4
  set shiftwidth=4
"设置匹配模式，类似当输入一个左括号时会匹配相应的那个右括号
  set showmatch
"去除vim的GUI版本中的toolbar
  set guioptions-=T
"在编辑过程中，在右下角显示光标位置的状态行
  set ruler
"默认情况下，寻找匹配是高亮度显示的，该设置关闭高亮显示
  set nohls
"使用此设置会快速找到答案，当你找要匹配的单词时，别忘记回车
  set incsearch
"如果没有下列行，加上吧
  if &term=="xterm"
  set t_Co=8
  set t_Sb=^[[4%dm
  set t_Sf=^[[3%dm
  endif

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif



"语言设置
set langmenu=zh_CN.UTF-8
set helplang=cn

"tab设置
map <F6> :tabprevious<CR>
map <F7> :tabnext<CR>
map <F5> :tabnew .<CR>
imap <F6> <ESC>:tabprevious<CR>i
imap <F6> <ESC>:tabnext<CR>i
imap <F5> <ESC>:tabnew .<CR>i

"状态栏
set statusline=%<[%n][%f]%m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).':'.&ff.']'}%y\ [%l,%v][%p%%]
set laststatus=2

"配色
colorscheme koehler
