"vundle
 set nocompatible               " be iMproved
 filetype off                   " required!

 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required! 
 Bundle 'gmarik/vundle'

 " My Bundles here:
 "
 " original repos on github
 Bundle 'tpope/vim-fugitive'
 Bundle 'Lokaltog/vim-easymotion'
 Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
 Bundle 'tpope/vim-rails.git'
 " vim-scripts repos
 Bundle 'L9'
 Bundle 'FuzzyFinder'
 " non github repos
 Bundle 'git://git.wincent.com/command-t.git'
 " ...

 filetype plugin indent on     " required!
 "
 " Brief help
 " :BundleList          - list configured bundles
 " :BundleInstall(!)    - install(update) bundles
 " :BundleSearch(!) foo - search(or refresh cache first) for foo
 " :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..

Bundle 'https://github.com/Lokaltog/vim-powerline.git'
Bundle 'https://github.com/Shougo/neocomplcache.git'
Bundle 'nanotech/jellybeans.vim'



if has("syntax")
  syntax on
endif

"自定义设置
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

"不兼容vi
set backspace=indent,eol,start

"
set nu

" ambiwidth 默认值为 single。在其值为 single 时，
" 若 encoding 为 utf-8，gvim 显示全角符号时就会
" 出问题，会当作半角显示。
set ambiwidth=double
set autoread " 自动重新加载外部修改内容

"兼容autochdir
if exists('+autochdir')
    set autochdir
else
    autocmd BufEnter * silent! lcd %:p:h:gs/ /\\ /
endif

"文字编码加入utf8
" 设定默认解码
set fileencodings=utf-8,gbk,gb18030,gb2312
set termencoding=utf-8,gbk,gb18030,gb2312
set fileformats=unix
set encoding=prc


"自动缩排
set ai

"搜索不分大小写
set ic

"标识关键字
set hls

:map <F6> :tabprevious<CR>
:map <F7> :tabnext<CR>
:map <F5> :tabnew .<CR>
:map <F3> :match Ignore /\r$/<CR>
set pastetoggle=<F8>



"设置状态栏
"set statusline=%<[%n][%f]%m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).':'.&ff.']'}%y\ [%l,%v][%p%%]
set laststatus=2

"配色
"colorscheme elflord


"colors jellybeans 插件 
colors jellybeans 



"ctags
set tags=tags

" vim-powerline
"
set t_Co=256
"let g:Powerline_symbols = 'unicode'


"neocomplcache
"NeoComplCacheEnable
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-y>  neocomplcache#close_popup()
inoremap <expr><C-e>  neocomplcache#cancel_popup()




